server:
  port: 9001

spring:
  application:
    name: question-service

  data:
    mongodb:
      database: question-service-db
      username: rootuser
      password: rootpass
      authentication-database: admin
      port: 27017
      host: localhost
